#!/bin/bash

if [ `whoami` != "root" ]; then echo "Please run as root" >&2; exit 1; fi

cd `dirname $0`

TTY=/dev/ttyAMA0

echo "marcel-mobile running on $TTY"
flock -n $TTY -c ./src/broker > $TTY < $TTY
