#!/bin/bash


stty -F /dev/ttyAMA0 115200 cs8

#mkfifo /dev/ttyAMA0 2>/dev/null

proxy_out() {
	mkfifo $1 2>/dev/null
	chmod a+w $1 2>/dev/null
	while true; do
	(
		while read line; do
			echo -e -n "$2 $line\r\n";
			echo -e -n "$2 $line\r\n" >&2
		done
	) < $1
	done &
}

proxy_in() {
	mkfifo $1 2>/dev/null
	chmod a+r $1 2>/dev/null
	chmod o-w $1 2>/dev/null
	mkdir -p /tmp/.marcel-mobile/proxy_in
	echo "$1" > /tmp/.marcel-mobile/proxy_in/$2
	while true; do sleep 999999999; done > $1 &
}


# Read loop from ttyAMA0
# while true; do
# 	(
# 		while read line; do
# 			char=${line::1}
# 			cmd=$(echo $line | cut -c3-100000)
# 			out=$(cat /tmp/.marcel-mobile/proxy_in/$char 2>/dev/null)
# 			if [ -n "$out" ]; then
# 				echo $cmd 2>&1
# 				echo $cmd > $out;
# 			else
# 				echo "Unknown callback : $line" 1>&2;
# 			fi
# 		done
# 	) < /dev/ttyAMA0
# done &


# Main
proxy_out /dev/motors s
proxy_out /dev/roam t
#proxy_in /dev/us u
#proxy_in /dev/odo o


####
while true; do sleep 100; done
