#!/bin/bash

# This script makes continous queries to the robot for odometry and US sensors


while [ ! -p /dev/robot ]; do sleep 1; done

echo "o 100" > /dev/robot

while true; do
	echo "z" > /dev/robot
	sleep 0.1
done